name       : etlegacy
version    : 2.75
release    : 1
source     :
    - https://github.com/etlegacy/etlegacy/archive/v2.75.tar.gz : 846027d9bf3ca1a410bd2d3e1e72da9ae4686dbf5194dbc34bca92ab5964ffc4
license    : GPL-3.0-or-later
component  : games.action
summary    : "Wolfenstein: Enemy Territory compatible client/server"
description: |
    ET: Legacy is based on the source code of the Wolfenstein: Enemy Territory. 
    The main goal of this project is to fix bugs, remove old dependencies and 
    make it playable on all major operating systems while still remaining 
    compatible with the ET 2.60b version and as many of its mods as possible.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(lua)
    - pkgconfig(minizip)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(sqlite3)
    - pkgconfig(theora)
    - pkgconfig(vorbis)
setup      : |
    %cmake . \
        -DCROSS_COMPILE32=OFF \
        -DBUILD_SERVER=OFF \
        -DBUILD_CLIENT=ON \
        -DBUNDLED_LIBS=OFF \
        -DFEATURE_AUTOUPDATE=OFF \
        -DINSTALL_OMNIBOT=OFF \
        -DINSTALL_DEFAULT_BASEDIR=/usr/share/etlegacy \
        -DINSTALL_DEFAULT_MODDIR=share/etlegacy
build      : |
    %make
install    : |
    %make_install

    install -D -m00644 docs/game/anticheat.html $installdir/usr/share/doc/etlegacy/anticheat.html
    install -D -m00644 docs/INSTALL.txt $installdir/usr/share/doc/etlegacy/INSTALL.txt

    install -d -m00755 $installdir/usr/share/etlegacy/legacy/
    install -m00644 legacy/*.{pk3,so} $installdir/usr/share/etlegacy/legacy

    rm $installdir/usr/share/etlegacy/*.txt
